### ISSUE TITLE
Error I got:

### ISSUE THREAD

**Issue by sigarett** [CraftPig/sweps_scpsl_items#1]
[SCP: SL Items] ParticleEmitter: Couldn't make emitter! Too many emitters!
  1. unknown - lua/entities/scp244b_placed.lua:60

**Comment by Aaronek10** [comment]
When this happends?

**Comment by sigarett** [comment]
> When this happends?

Happened after I placed a few around the map, I would say probably 5 or more, and it started spamming that error.

**Comment by Aaronek10** [comment]
Okey, let me check code and i will try to investigate

**Comment by Aaronek10** [comment]
Should be fixed now.
